# -*- coding: utf-8 -*-
"""RandomForest_test

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FrpsXMdhpaD5rikBLnhL1nuY4I4uSCjP
"""

import seaborn as sns
import pandas as pd
import numpy as np

df=sns.load_dataset('iris')
df.head()

df['species'].unique()

df.isnull().sum()

df=df[df['species']!='setosa']

df.head()

df['species']=df['species'].map({'versicolor':0,'virginica':1})
df.head()

X=df.iloc[:,:-1]
y=df.iloc[:,-1]

X

y

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

from sklearn.ensemble import RandomForestClassifier
clf= RandomForestClassifier(criterion="gini",max_depth=8, min_samples_split=10,random_state=5)

clf.fit(X_train, y_train)

clf.feature_importances_

y_pred= clf.predict(X_test)

y_pred

from sklearn.metrics import confusion_matrix
confusion_matrix (y_test, y_pred)

from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

from sklearn.model_selection import cross_val_score
cross_val_score(clf,X_train,y_train,cv=10)

from sklearn.metrics import classification_report
print(classification_report(y_pred, y_test))

